### ISSUE TITLE
Question: How to make it work on windows ?

### ISSUE THREAD

**Issue by bikerdba** [oveas/sqltex#4] opened 2022-01-24 16:20 UTC
I am having difficulty making it work on windows. I am able to install and run the exe, is there a possibility for you to create a runbook on how to make it work on Windows ?

I can help by providing steps I am taking from my side. Please let me know if you want to undertake this ?

Thanks a lot,
Amit Singh

**Comment by oveas** [comment] 2022-01-25 08:10
I'm not sure what the issue is: if you are able to install and tun the exe, basically you're done. But keep in mind this is a command-line tool, maybe that's what you miss.

You just need to copy the 3 files (`SQLTeX.exe`, `SQLTeX.cfg` and `SQLTeX_r.dat`) all to the same location, let's say `C:\SQLTeX`.
Then you can open a DOS box (`cmd`) and type:
`C:\> cd \SQLTeX`
`C:\SQLTeX> SQLTeX.exe --help`

That should get you started.
Hope this helps.

**Comment by oveas** [comment] 2022-02-21 12:30
I haven heard back from you, so I assume my answer was enough help.
Closing this issue.

**Closed as completed by oveas** 2022-02-21 12:30 UTC
